### ISSUE TITLE
Bug GTS

### ISSUE THREAD

**Issue by Heriptik** [EnvyWare/EnvyGTS#1]
Hello, i have tested your mod in my Test server and i have a bugs lot to report : 
You can see this video : [https://drive.google.com/file/d/1PZqGwO8dMovkRZFVdAZIF8a_TFVxDhbl/view?usp=sharing](https://drive.google.com/file/d/1PZqGwO8dMovkRZFVdAZIF8a_TFVxDhbl/view?usp=sharing)

 - There is a bug when selling pokémons / items it is not sent to the buyer
 - The tax is not applied (I set it to 0.95)
 - The money is withdrawn but not sent to the salesman

I use latest catserver, my plugins is : CMI 9.0.4.5, EcoBridgeSpigot-1.0.2, Vault 1.7.3
My plugin economy is CMI.

My mod is : Pixelmon 8.2.0 server, ReforgedGTS-Forge-0.5.0

thanks for your help =)

Edit : I don't have error in my console

**Comment by danorris709** [comment]
Fixed in latest version
