### ISSUE TITLE
Suggestion - placeholders for broadcast 

### ISSUE THREAD

**Issue by SnowBlitzz** [EnvyWare/EnvyGTS#21]
Would be nice to be able to set create-trade-broadcast to something like `GTS > %player% added a %ability% %iv_percentage% IV %shiny% %name% for ₽%cost%` so it tells the player a rough summary of the pokemon being put up there. This is so they dont have to open the gts menu each time just to see some low stats pokemon they're uninterested in. 

Other servers might wanna use a different broadcast format so adding the other placeholders might help. Since it already works for webhooks I don't see why not for the in-game broadcast.

**Comment by danorris709** [comment]
Added for next version
