### ISSUE TITLE
Suggestion - limit stuff in expired trades

### ISSUE THREAD

**Issue by SnowBlitzz** [EnvyWare/EnvyGTS#22]
1. Option to disallow player to put up more items/pokemon for selling when their expired trades reached a certain limit (they'd have to claim them to be able to sell again). Otherwise they would be using the expired trades page as an infinite storage

**Comment by danorris709** [comment]
Expired trades was removed in latest version

**Comment by SnowBlitzz** [comment]
> Expired trades was removed in latest version

Wouldn't that be a problem for items? if someone has a full inventory.
