### ISSUE TITLE
Minor Bug - Enchants are still visible for listed items with HIDE_ENCHANTS flag

### ISSUE THREAD

**Issue by SnowBlitzz** [EnvyWare/EnvyGTS#23]
These are usually the custom items, where the enchantment is just there to make the item glow and the enchant itself is hidden in the lore display.

**Comment by danorris709** [comment]
Can you show me a screenshot and the config for said screenshot please?

**Comment by SnowBlitzz** [comment]
![image](https://user-images.githubusercontent.com/7488382/205120200-c4d444a0-f7d9-43d4-84a1-3c999651dc2b.png)
![image](https://user-images.githubusercontent.com/7488382/205120269-3d50e4a3-d5dd-4a2e-b8c4-b2822c36a38e.png)

**Comment by danorris709** [comment]
Fixed for next version
