### ISSUE TITLE
Suggestion - command to retrieve expired listings

### ISSUE THREAD

**Issue by lankyboy01** [EnvyWare/EnvyGTS#26]
I am suggesting a feature that offline listing are stored the same way the expired listings were the the old GUI that can all be claimed via `gts claim` since they are kind of just disappearing currently.

When a user logins, they will get a notification saying they have expired listings
If they player inventory is full, either not allow items to be claimed or just drop them on the player.

**Comment by danorris709** [comment]
Added in next version
