### ISSUE TITLE
Some placeholders have wrong data

### ISSUE THREAD

**Issue by SirDoof** [EnvyWare/EnvyGTS#28]
The following occurs in the webhooks:
**purchaser-item:**
`%buyer%` returns the seller and not the buyer
`%item%` returns as Air
`%amount%` returns as 0

**purchaser-pokemon:**
`%buyer%` placeholder returns the seller and not the buyer

**remover-item:**
`%item%` returns as Air
`%amount%` returns as 0

In the sprite-config for the guis & all pokemon webhooks:
`%held_item%` returns as Air when no held item is present. `None` would be more fitting imo

**Comment by danorris709** [comment]
Should be fixed for next version
