### ISSUE TITLE
Price & Duration Corrections

### ISSUE THREAD

**Issue by SirDoof** [EnvyWare/EnvyGTS#29]
In the config.yml, I have the following settings:
min-trade-duration: 3600 (1 hour)
default-trade-duration-seconds: 172800 (2 days)
max-trade-duration-seconds: 172800
max-price: 500000.0

Selling an item with `/gts sell` doesn't support the new time format in the duration argument and I think it should instead of just seconds. It also doesn't respect the max duration and you can go above the config value.

When selling a Pokémon in the UI, you can set a higher price that goes above the max-price.
The same happens with the duration. I have it at max 2 days but I can type 360d to go above.

**Comment by danorris709** [comment]
Sorted all this for the next version
