### ISSUE TITLE
GTS Suggestion

### ISSUE THREAD

**Issue by Mikirae** [EnvyWare/EnvyGTS#31]
I'd like to suggest adding hover-able characteristics to the GTS broadcast, so that when people see
"Mikirae has added a 69% Lopunny to GTS", they can hover over it and get all the required information.

**Comment by danorris709** [comment]
The JSON format for tellraw is already supported by all lang keys in my mods :) 

You can find that [here](https://misode.github.io/text-component/)

**Comment by Mikirae** [comment]
Okay, thank you kind sir!
