### ISSUE TITLE
[Suggestion] Add enchantment list and Lore placeholders for item webhooks

### ISSUE THREAD

**Issue by Mike5357** [EnvyWare/EnvyGTS#33]
When a player publishes an item such as an enchantment book, it just comes through as "Enchanted Book" without any way of telling the actual enchantment applied to it. Please add a placeholder that allows enchantment information to be displayed, as well as lore of the item

Thanks :)

**Comment by Mike5357** [comment]
(note: %lore% *seems* to actually parse, but parses as just an empty string)

**Comment by danorris709** [comment]
Added for latest version
