### ISSUE TITLE
[EnvyGTS 4.1.8] Duplication Glitch

### ISSUE THREAD

**Issue by Subtrahxnd** [EnvyWare/EnvyGTS#37]
![image](https://github.com/EnvyWare/EnvyGTS/assets/118085660/a4d23f58-f284-44f8-9299-4b33b637bec6)
Whenever the first page of GTS is Full, the first Item/Pokemon, which should be on the second page overrides the back to previous page button and can be bought infinitely.

**Comment by danorris709** [comment]
This is an error in the config
