### ISSUE TITLE
GTS Crash on Startup

### ISSUE THREAD

**Issue by thewickening** [EnvyWare/EnvyGTS#43]
Just updated to 5.0.1 and it crashes on startup on my test server. 1.16.5

https://pastebin.com/PQ0EyTpr

**Comment by danorris709** [comment]
What is in your config? I tested this on a 1.16.5 server, deleted my configs and let them re-generate, and didn't get this crash?

Perhaps are your configs from a pre-5.0.0 version?

**Comment by thewickening** [comment]
> What is in your config? I tested this on a 1.16.5 server, deleted my configs and let them re-generate, and didn't get this crash?
> 
> Perhaps are your configs from a pre-5.0.0 version?

Hey sorry for the delay. I regenned configs and still crash on startup, it also seems it is having a hard time generating the SQLite database.

https://pastebin.com/931vEeP5

https://pastebin.com/EYsb6f6A

**Comment by danorris709** [comment]
Oh I see the issue with the new config. I was playing around testing an H2 database setup, and accidentally left that as the default config despite it not being implemented! 

I shall release a new version in a second, if you could let me know if you're still experiencing the issue (with fresh configs).
